### ISSUE TITLE
Awesome! -> one more thing ;)

### ISSUE THREAD

**Issue by HerbstLukas** [MaxHasADHD/TraktKit#1]
Thank you for this awesome framework. 
I'm currently an ongoing swift developer and this is an awesome example how to build a nice framework to talk to an API! :) 

One more thing: 
It would be nice if the TraktManager would respond directly with Swift Models (structs or classes)
Don't know if you have planned to add something like that later? (:

**Comment by MaxHasADHD** [comment]
I built this framework while working on my app Television Time, which uses Core Data. I built a separate, private framework that has the models with Core Data so they save, although for parsing the data I guess returning them as arrays and dictionaries with struct/class models would be nice so I might think about doing this in the future. Current focus is getting every Trakt method added, documented and working. Very close to finishing that and then I'll see about object models :)

**Comment by MaxHasADHD** [comment]
Look into the branch "Native-Objects" which begins this.
