### ISSUE TITLE
getUserCollection(type: .Shows) gives error

### ISSUE THREAD

**Issue by AnthonyFaxlandez** [MaxHasADHD/TraktKit#24]
When you call TraktManager.sharedManager.getUserCollection(type: .Shows) it returns this error:

`The data couldn’t be read because it is missing.`

It looks like this is related to the JSON it's trying to parse. Maybe some of the JSON has changed?

**Comment by MaxHasADHD** [comment]
I'll take a look into this.

**Comment by MaxHasADHD** [comment]
Uploading a fix soon, sorry for the delay I've been so busy.
