### ISSUE TITLE
No avatar image in profile (or get settings)

### ISSUE THREAD

**Issue by iFonny** [MaxHasADHD/TraktKit#28]
```
  "images": {
    "avatar": {
      "full": "https://walter.trakt.tv/images/users/004/639/754/avatars/large/112091c7b0.jpg"
    }
  }
```
is in trakt api but not in the wrapper

**Comment by MaxHasADHD** [comment]
Hi there, thank's for reporting! I'll take a look and try to add this.

**Comment by ghost** [comment]
@MaxHasADHD Any news on this? 

Thanks for this amazing wrapper!

**Comment by MaxHasADHD** [comment]
I just merged a PR which added support for this.
