### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by skarchmit** [MaxHasADHD/TraktKit#33]
I tried implementing only the login and logout functionality from the example.
I hit sign out and It deletes the accessToken, however when I click log in after signing out, it doesn’t present me with a login screen, but immediately dismisses the safariServices, retrieving the accessToken. What if I want to login with a different Trakt Account?

iOS 12.1.4

Is this a known issue? 

Cleaning out cache manually from settings works, but not ideal since you can’t set up a one time cache nor clear it out for the used.

**Comment by MaxHasADHD** [comment]
SFSafariViewController's cache can't be cleared by your app as far as I'm aware unfortunately.
