### ISSUE TITLE
Title in TraktShowTranslation should be an optional String

### ISSUE THREAD

**Issue by schaechtele** [MaxHasADHD/TraktKit#52]
Hi @MaxHasADHD,
first, thanks for your awesome work!

I found one issue when using the `getShowTranslations` method. As the translated title returned from Trakt can be empty, `title` should be an optional String in `TraktShowTranslation`. I received a parsing error and that's how I found out. I think that  the title is empty in a translation when the title is the same as in the original language.

**Comment by MaxHasADHD** [comment]
Oh, thanks for letting me know! I'll look into getting that fixed

**Comment by MaxHasADHD** [comment]
@schaechtele The latest version (1.2.3) fixes this, and adds support for rate limits.

**Comment by schaechtele** [comment]
Great, thank you!!!
