### ISSUE TITLE
getPeopleInEpisode fails

### ISSUE THREAD

**Issue by envoza** [MaxHasADHD/TraktKit#56]
Hi, calls to getPeopleInEpisode fail due to "episode_count" not being present for episodes.  In TVCastMember and TVCrewMember episodeCount needs to be optional to parse successfully.

The unit test for getPeopleInEpisode reports success, but actually fails and does not check the returned values as there is no check for the result being invalid.  This appears to be the case with some other unit tests I've looked at.

I'm putting together a pull request (my first ever) with fixes for the model and test.

**Comment by MaxHasADHD** [comment]
@envoza Thank you for reporting, and sorry it's taken so long, I am pushing a fix out now.
