### ISSUE TITLE
OAuth Issue

### ISSUE THREAD

**Issue by sergiosrgtc** [MaxHasADHD/TraktKit#6]
Hi, first of all thanks for this nice framework, everything is working except for the OAuth required methods. I have followed your examples and when the app try to authenticate it stops on this screen: 
![screen shot 2016-11-18 at 12 44 26](https://cloud.githubusercontent.com/assets/15271885/20433928/cc7a97c2-ad8c-11e6-81ae-aa6bb5b6110c.png)

I am using SWIF 3 and my guess is that this method is not being called properly:
 
This gave me an error so i changed to the method bellow   
func application(application: UIApplication, handleOpenURL url: NSURL) -> Bool {
....
}

I guess this is the Swift 3 aproach
func application(_ application: UIApplication, handleOpen url: URL) -> Bool {
...
}

Can you please help with this or provide an swift 3 example of how to use oauth methods to get the user watched movies for example.  

Regards,

Sergio

**Comment by MaxHasADHD** [comment]
Hi there! Sorry for the late reply. It looks like your app on Trakt.tv is set up to use the pin authentication. I have not tested this part yet, but it should present a login for the user to enter their Trakt.tv details. I'll update examples and add more documentation soon.

**Comment by sergiosrgtc** [comment]
Hi Max, I figured it out eventually, i was able to login but my it was my Redirect uri was wrong so i was not able to return to my app. It is working now, thanks.
